services:
  pg_1:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_HOST_AUTH_METHOD: trust
  pg_2:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_HOST_AUTH_METHOD: trust
  cockroachdb_1:
    image: cockroachdb/cockroach:v23.2.4
    ports:
      - "5434:26257"
    command: start-single-node --insecure
  cockroachdb_2:
    image: cockroachdb/cockroach:v23.2.4
    ports:
      - "5435:26257"
    command: start-single-node --insecure
