addSbtPlugin("org.scalameta"      % "sbt-scalafmt"                  % "2.4.6")
addSbtPlugin("org.scala-native"   % "sbt-scala-native"              % "0.4.14")
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "1.3.2")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"                  % "0.11.0")
addSbtPlugin("org.jmotor.sbt"     % "sbt-dependency-updates"        % "1.2.7")
addSbtPlugin("org.typelevel"      % "sbt-typelevel-ci-release"      % "0.5.0-RC9")
addSbtPlugin("org.typelevel"      % "sbt-typelevel"                 % "0.5.0-RC9")
