addSbtPlugin("org.scalameta"             % "sbt-scalafmt"                  % "2.4.6")
addSbtPlugin("com.github.sbt"            % "sbt-dynver"                    % "5.0.1")
addSbtPlugin("org.scala-native"          % "sbt-scala-native"              % "0.4.14")
addSbtPlugin("org.portable-scala"        % "sbt-scala-native-crossproject" % "1.3.1")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"                  % "0.11.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"                  % "0.4.3")
addSbtPlugin("org.jmotor.sbt"            % "sbt-dependency-updates"        % "1.2.7")
addSbtPlugin("com.github.sbt"            % "sbt-pgp"                       % "2.2.1")
